config/routes.rb
Rails.application.routes.draw do
  get 'cod_accounts/cc_date'
  get 'cod_accounts/selected'
  get 'cod_accounts/accounts'
  get 'cod_accounts/verified'
  resources :cod_accounts
  devise_for :users
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cod_accounts#cc_date'
end

app/models/cod_account.rb
class CodAccount < ApplicationRecord
  validates :amount_received, presence: true
  validate :owed_and_received
  validate :check

  def owed_and_received
    if !errors.any?
      if !$value || $value != amount_received
        $value = amount_received
        if amount_received != amount_owed
          errors.add(:amount_received, "is not equal to amount owed. Press 'Update' again to continue.")
        end
      end
    end
  end

  def check
    if !errors.any?
      if received_as == 'Check' && !check_numb.present?
          errors.add(:check_numb, "is required when check is received.")
      end
    end
  end

end

app/controllers/cod_accounts_controller.rb
class CodAccountsController < ApplicationController
  before_action :set_cod_account, only: [:show, :edit, :update, :destroy]
  before_action :set_drop_downs, only: [:new, :edit, :update, :create]

  # GET /cod_accounts
  def index

    if params[:cost_ctr] || params[:ship_date]
      # looks like something may have changed
      @cc = params[:cost_ctr]
      if params[:ship_date]
        @ship_date = params[:ship_date].to_date
        ship_date = params[:ship_date] + ' 05:00:00'
        session[:ship_date] = ship_date.to_date
      else
        @ship_date = Date.current
        session[:ship_date] = Date.current
      end
      session[:cc] = params[:cost_ctr]
    end
    if current_user.cod_role != 'Accounting'
      invoices = Invhead.where(cost_ctr: session[:cc]).where("ship_date = ?", session[:ship_date]).where("terms_code LIKE :prefix", prefix: "COD%")
      invoices.each do |i|
        # create cod_account records for this cost center and ship date if they don't already exist
        if i.order_numb != "MISC"
          ca = CodAccount.find_by invoice_numb: i.invoice_numb
          if !ca
            # there is no existing COD record so create one with initial values
            codaccount = CodAccount.new
            codaccount.invoice_numb = i.invoice_numb
            codaccount.ship_date = i.ship_date
            invview = Invheadview.find_by invoice_numb: i.invoice_numb
            if invview
              if !invview.sub_total
                invview.sub_total = 0
              end
              if !invview.charged_frt
                invview.charged_frt = 0
              end
              codaccount.amount_owed = (invview.sub_total + invview.charged_frt).round(2)
            else
              codaccount.amount_owed = 0
            end
            ordhead = Ordhead.find_by order_numb: i.order_numb, rel_numb: i.rel_numb
            if ordhead
              codaccount.route_code = ordhead.route_code
              if codaccount.route_code.length == 1
                # need to prefix 1 digit route codes with blank to make them sort correctly
                codaccount.route_code.insert(0, '0')
              end
              codaccount.cust_code = ordhead.cust_code
              codaccount.cust_name = ordhead.cust_name
              codaccount.cost_ctr = ordhead.cost_ctr
              codaccount.logistics_completed = false
              codaccount.accounting_completed = false
              codaccount.save(:validate => false)
            end
          end
        end
      end
    end
    case current_user.cod_role
    when 'Admin'
      # show all the COD records for this CC and shipping date
      @cod_accounts = CodAccount.where(cost_ctr: session[:cc]).where("ship_date = ?", session[:ship_date])
    when 'Logistics'
      # show all the COD records for this CC and shipping date
      @cod_accounts = CodAccount.where(cost_ctr: session[:cc]).where("ship_date = ?", session[:ship_date])
    else
      # must be accounting
      # show all the COD records for this CC  completed by logistics but not completed by accounting
      @cod_accounts = CodAccount.where(cost_ctr: session[:cc]).where(logistics_completed: true).where.not(accounting_completed: true)
    end
  end

  # GET /cod_accounts for accounting
  def accounts

    if params[:cost_ctr]
      # looks like something may have changed
      @cc = params[:cost_ctr]
      session[:cc] = params[:cost_ctr]
    end
    @cod_accounts = CodAccount.where(cost_ctr: session[:cc]).where(logistics_completed: true).where.not(accounting_completed: true)
  end

  def verified
    i = 0
    cod_count = CodAccount.where(cost_ctr: session[:cc]).where(logistics_completed: true).where.not(accounting_completed: true).length
    while i < cod_count
      i += 1
      verifiedi = 'verified'+i.to_s
      if params[verifiedi] == '1'
        # check box selected
        idi = 'id'+i.to_s
        cod_account = CodAccount.find_by id: params[idi]
        cod_account.accounting_completed = true
        cod_account.accounting_complete_date = Date.current
        cod_account.save
      end
    end
    redirect_to cod_accounts_accounts_path, notice: 'CODs were successfully verified.'
  end

  # GET /cod_accounts/1
  def show
  end

  # GET /cod_accounts/new
  def new
    @cod_account = CodAccount.new
  end

  # GET /cod_accounts/1/edit
  def edit
  end

  # POST /cod_accounts
  def create
    @cod_account = CodAccount.new(cod_account_params)

    respond_to do |format|
      if @cod_account.save
        format.html { redirect_to cod_accounts_url, notice: 'COD account was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /cod_accounts/1
  def update
    respond_to do |format|
      if @cod_account.update(cod_account_params)
        if @cod_account.logistics_completed && current_user.cod_role == 'Logistics'
          # Just completed by logistics, store the user id
          @cod_account.logistics_agent = current_user.email
          @cod_account.logistics_complete_date = DateTime.now
          @cod_account.save
        end
        if @cod_account.accounting_completed && current_user.cod_role == 'Accounting'
          # Just completed by accounting, store the user id
          @cod_account.accounting_complete_date = DateTime.now
          @cod_account.save
        end
        format.html { redirect_to cod_accounts_url, notice: 'COD account was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /cod_accounts/1
  def destroy
    @cod_account.destroy
    respond_to do |format|
      format.html { redirect_to cod_accounts_url, notice: 'COD account was successfully deleted.' }
    end
  end

  def cc_date
    if !user_signed_in? || !current_user.cod
      redirect_to signout_path and return
    else
      if !session[:ship_date]
        session[:ship_date] = Date.current
      end
      @ship_date = session[:ship_date]
      # @ship_date = session[:ship_date].strftime('%Y-%m-%d')
      @ccs = ['NJ', 'IL', 'GA', 'TX', 'CO']
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cod_account
      @cod_account = CodAccount.find(params[:id])
    end

    def set_drop_downs
      @reasons = ["Driver Error",
      "Drop Approved by Credit",
      "Drop Approved by Regional Manager",
      "Returned - Credit in process",
      "Short Paid - Pricing issue - Sales to investigate",
      "Short Paid - Product missing - Credit pending"]
      @received_as = ["Cash", "Check"]
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def cod_account_params
      params.require(:cod_account).permit(:ship_date, :invoice_numb, :route_code, :cust_code, :cust_name, :cost_ctr, :logistics_complete_date,
        :accounting_complete_date, :reason_code, :reason_details, :logistics_completed, :accounting_completed, :logistics_agent, :received_as,
        :amount_owed, :amount_extra, :amount_received, :amount_credit, :credit_amount, :check_numb, :notes)
    end
end

app/helpers/cod_accounts_helper.rb
module CodAccountsHelper
end

app/views/cod_accounts/_form.html.erb
<%= form_with(model: cod_account, local: true) do |form| %>
  <% if cod_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cod_account.errors.count, "error") %> prohibited this cod_account from being saved:</h2>

      <ul>
      <% cod_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Ship date</th>
        <th>Invoice number</th>
        <th>Route code</th>
        <th>Customer code</th>
        <th>Customer name</th>
        <th>Cost center</th>
        <th>Amount owed</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= display_date(@cod_account.ship_date) %></td>
        <td><%= @cod_account.invoice_numb %></td>
        <td><%= @cod_account.route_code %></td>
        <td><%= @cod_account.cust_code %></td>
        <td><%= @cod_account.cust_name %></td>
        <td><%= @cod_account.cost_ctr %></td>
        <td><%= @cod_account.amount_owed %></td>
      </tr>
    </tbody>
  </table>

  <% if current_user.cod_role != 'Logistics' %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Logistics user</th>
          <th>Logistics completed</th>
          <% if current_user.cod_role != 'Accounting' %>
            <th>Accounting completed</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @cod_account.logistics_agent %></td>
          <td><%= display_date(@cod_account.logistics_complete_date) %></td>
          <% if current_user.cod_role != 'Accounting' %>
            <td><%= display_date(@cod_account.accounting_complete_date) %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  <% end %>

  <% if current_user.cod_role != 'Accounting' %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th><%= form.label :reason_code %></th>
          <th><%= form.label :received_as %></th>
          <th><%= form.label :check_numb, "Check number" %></th>
          <th><%= form.label :amount_received %></th>
          <th><%= form.label :logistics_completed %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td> <%= form.select :reason_code, @reasons, {:include_blank => true}, {:value => params[:cod_account_reason_code]} %> </td>
          <td> <%= form.select :received_as, @received_as, {}, {:value => params[:cod_account_received_as] } %> </td>
          <td> <%= form.text_field :check_numb, id: :cod_account_check_numb %></td>
          <td> <%= form.number_field :amount_received, id: :cod_account_amount_received, step: 0.01 %></td>
          <td> <%= form.check_box :logistics_completed, id: :cod_account_logistics_completed %> </td>
        </tr>
      </tbody>
    </table>
  <% else %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Reason code</th>
          <th>Logistics user</th>
          <th>Recieved as</th>
          <th>Check Number</th>
          <th>Amount recieved</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td> <%= @cod_account.reason_code %> </td>
          <td> <%= @cod_account.logistics_agent %> </td>
          <td> <%= @cod_account.received_as %> </td>
          <% if @cod_account.check_numb %>
            <td> <%= @cod_account.check_numb %> </td>
          <% else %>
            <td>  </td>
          <% end %>
          <td> <%= @cod_account.amount_received %> </td>
        </tr>
      </tbody>
    </table>
    <div class="field">
      <%= form.label :accounting_completed, "Accounting verified" %>
      <%= form.check_box :accounting_completed, id: :cod_account_accounting_completed %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :cod_account_notes %>
  </div>

  <div class="actions">
    <%= form.submit "Update" %>
  </div>
<% end %>

app/views/cod_accounts/accounts.html.erb
<p id="notice"><%= notice %></p>

<h2>COD Accounts For CC: <%= @cc %> </h2>

<%= form_with url: cod_accounts_verified_path, local: true, method: 'get' do |f| %>
<table id="normal_dt"  class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <th>Ship date</th>
      <th>Route code</th>
      <th>Invoice numb</th>
      <th>Cust code</th>
      <th>Cust name</th>
      <th>Amount owed</th>
      <th>Verified?</th>
      <th hidden>ID</th>
    </tr>
  </thead>

  <tbody>
    <% x = 0 %>
    <% @cod_accounts.each do |cod_account| %>
      <% x += 1 %>
      <% verifiedi = "verified"+x.to_s %>
      <% idi = "id"+x.to_s %>
      <tr>
        <td><%= display_date(cod_account.ship_date) %></td>
        <td><%= cod_account.route_code %></td>
        <td><%= cod_account.invoice_numb %></td>
        <td><%= cod_account.cust_code %></td>
        <td><%= cod_account.cust_name %></td>
        <td><%= cod_account.amount_owed %></td>
        <td><%= f.check_box verifiedi %> </td>
        <td hidden ><%= f.text_field idi, :value => cod_account[:id].to_s, :readonly => true %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= f.submit "Verify CODs" %>
<% end %>

app/views/cod_accounts/cc_date.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.cod_role != 'Accounting' %>
  <h2>Enter Cost Center And Shipping Date</h2>
  <%= form_with url: cod_accounts_path, local: true, method: 'get' do |f| %>
    <%= f.label(:cost_ctr, 'Cost Center:') %>
    <%= f.select :cost_ctr, @ccs, {}, id: "cost_ctr"  %>
    <%= f.label(:ship_date, 'Shipping Date:') %>
    <%= f.date_field :ship_date, id: "ship_date", :value => @ship_date %></td>
    <%= f.submit "Enter" %>
  <% end %>
<% else %>
  <h2>Enter Cost Center</h2>
  <%= form_with url: cod_accounts_accounts_path, local: true, method: 'get' do |f| %>
    <%= f.label(:cost_ctr, 'Cost Center:') %>
    <%= f.select :cost_ctr, @ccs, {}, id: "cost_ctr"  %>
    <%= f.submit "Enter" %>
  <% end %>
<% end %>

app/views/cod_accounts/edit.html.erb
<h2>Editing COD Account</h2>

<%= render 'form', cod_account: @cod_account %>
<br>

<%= link_to 'Back', cod_accounts_path, class: "btn btn-primary"  %>

app/views/cod_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.cod_role == 'Accounting' %>
  <h2>COD Accounts For CC: <%= @cc %> </h2>
<% else %>
  <h2>COD Accounts For CC: <%= @cc %> Ship Date: <%= display_date(@ship_date) %> </h2>
<% end %>

<table id="normal_dt"  class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <% if current_user.cod_role == 'Accounting' %>
        <th>Ship date</th>
      <% end %>
      <th>Route code</th>
      <th>Invoice numb</th>
      <th>Cust code</th>
      <th>Cust name</th>
      <th>Amount owed</th>
      <th></th>
      <% if current_user.cod_role == "Admin" %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @cod_accounts.each do |cod_account| %>
      <tr>
        <% if current_user.cod_role == 'Accounting' %>
          <td><%= display_date(cod_account.ship_date) %></td>
        <% end %>
        <td><%= cod_account.route_code %></td>
        <td><%= cod_account.invoice_numb %></td>
        <td><%= cod_account.cust_code %></td>
        <td><%= cod_account.cust_name %></td>
        <td><%= cod_account.amount_owed %></td>
        <% if current_user.cod_role == "Logistics" && cod_account.logistics_completed %>
          <td></td>
        <% else %>
          <td><%= link_to 'Edit', edit_cod_account_path(cod_account), class: "btn btn-primary" %></td>
        <% end %>
        <% if current_user.cod_role == "Admin" %>
          <td><%= link_to 'Delete', cod_account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cod_accounts/new.html.erb
<h2>New Cod Account</h2>

<%= render 'form', cod_account: @cod_account %>

<%= link_to 'Back', cod_accounts_path, class: "btn btn-primary"  %>