config/routes.rb
Rails.application.routes.draw do
  get 'cod_accounts/cc_date'
  get 'cod_accounts/selected'
  get 'cod_accounts/accounts'
  get 'cod_accounts/verified'
  resources :cod_accounts
  devise_for :users
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cod_accounts#cc_date'
end

app/views/layouts/_header.html.erb
<span class="primary-logo">
</span>
<span id="navbar">
  <% if user_signed_in? %>
    <span><%= link_to 'Find', cod_accounts_cc_date_path, class: "btn btn-primary" %></span>
    <span><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-primary" %></span>
  <% end %>
</span>
<h1 class="title">Cash On Delivery
</h1>
<% if user_signed_in? %>
  <span>Signed in as <%= current_user.email %></span>
<% else %>
  <span>No user currently signed in</span>
<% end %>
<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cash On Delivery</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="global">
      <div style="position: fixed; top: 0px; width: 100%; height: 8em; background-color: white; z-index: 100;">
        <%= render 'layouts/header' %>
      </div>
      <div style="margin-top: 8.5em;">
        <%= yield %>
      </div>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <script src="/assets/printPreview.js"></script>
    <script src="/assets/myjavascript.js"></script>
  </body>
</html>